package cropbuddy;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author DELL
 */
public class Sell_pro extends javax.swing.JFrame {

    /**
     * Creates new form Sell_pro
     */
    public Sell_pro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textField2 = new java.awt.TextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        textField3 = new java.awt.TextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        textField5 = new java.awt.TextField();
        jLabel8 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("SELL PRODUCT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 0, 280, 55);

        jLabel2.setFont(new java.awt.Font("Thunder", 0, 18)); // NOI18N
        jLabel2.setText("quantity");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 260, 50, 30);

        jLabel3.setFont(new java.awt.Font("The Bold Font", 0, 30)); // NOI18N
        jLabel3.setText("Enter product details");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 90, 350, 50);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select category--", "vegetable", "fruit", "seeds" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 160, 240, 30);

        jLabel4.setFont(new java.awt.Font("Thunder", 0, 18)); // NOI18N
        jLabel4.setText("Category");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 160, 70, 30);
        getContentPane().add(textField1);
        textField1.setBounds(280, 210, 240, 30);

        jLabel5.setFont(new java.awt.Font("Thunder", 0, 18)); // NOI18N
        jLabel5.setText("product description:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 380, 120, 40);

        jLabel6.setFont(new java.awt.Font("Thunder", 0, 18)); // NOI18N
        jLabel6.setText("product name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 210, 80, 30);

        textField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(textField2);
        textField2.setBounds(280, 260, 240, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kg", "gm", "ton", " " }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(520, 320, 60, 30);
        getContentPane().add(textField3);
        textField3.setBounds(280, 320, 240, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kg", "gm", "ton", " " }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(520, 260, 60, 30);

        jLabel7.setFont(new java.awt.Font("Thunder", 0, 18)); // NOI18N
        jLabel7.setText("upload photo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 520, 130, 40);

        textField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField5ActionPerformed(evt);
            }
        });
        getContentPane().add(textField5);
        textField5.setBounds(280, 380, 250, 110);

        jLabel8.setFont(new java.awt.Font("Thunder", 0, 18)); // NOI18N
        jLabel8.setText("price per unit");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 320, 80, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void textField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sell_pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sell_pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sell_pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sell_pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sell_pro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField5;
    // End of variables declaration//GEN-END:variables
}
